apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: kube-system
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:+8O4oxIi+Oxhz9kE0RNL6g/6I8kYt83Un8hjXp1EJqGUj7BWIeoQ/fXg7V9RhwmdXCtHvvolvGo=,iv:U+k6lE3WzYScc1MLc9rLewFQtUlO9twNWUibAfEQ9J4=,tag:l75BvnAPHo8jwVXWQPXb0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5gkmyjsuwlsucdvpt3z9sk3t6wdtnc20gf7cwvqa700mqauhsksjj0gj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMFFvQW9ER2xhUzA2M0F1
            dmxoUkZ1WnU1d3U2WHFaM2NtenRWckYvbUY0CnkxYTFTN0QvV0ZQd1p6OHkyUXNC
            SGZRTXRBckpuRjVjUjJ5QXNHWm9DUHcKLS0tIExwMk15eDdiaTh5Um1qcGdrN21h
            cjJXdUVEUkVzOWJPeFpuT3FVeVlNWEkKZY82KuPZUKw0fxjpcA2pUPcHgQBkNxgf
            IVOlPGoz0gA1DjIk4UqNzmiRo6PcgZ5A5vo4S+L6MvOyAt4UPJLubQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T16:54:15Z"
    mac: ENC[AES256_GCM,data:GaUB4nsoJtAxpvGI14EQrvBuhmh3NfzCSQEzNFYbZXecUq79mrE1D6ivxmVAa90kb0ARQ2892L6VvjcphGSds1xZGga2Zg4NhbbSR0vD+JId7CAlSPkb4KfSi7NroIaD7xMxq0HTPM4xHOIu8fo1mXAlMSq6LwVT8THJ4IkbU/k=,iv:Fg+MRS3HhDLWFYddaLTQLVfMx9eaagHqctSQGQvfs8A=,tag:pJofTyUquD+GjbKQRx0wiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
