apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
data:
    address: ENC[AES256_GCM,data:vUj2KRqi0BHBm8Jd5/Y/4LXkMkBAUR4hc5YQm9CZHDkLW2Zd+L4gfWcta8VG/iUaA4VN+0UHJ2WogNE12/T83DkdkBAN/RnUBcSAhImljswp5VTLW3l5f44zN76HSGRZ2G3J8Z+MZj4oyceE4HlWgm4/zdvqbhHHpVDUgus2L5Zrsz4BDu7ADg/XxRY6iaD/ndkDhn6/6YFCNdOZAGzL+r1LBAk=,iv:XIffcVPoLWn7d6nNH80omF3k9XwcVtZ0ma0YnWfxyqM=,tag:TkpSnYcUiLHNWirqT+viKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5gkmyjsuwlsucdvpt3z9sk3t6wdtnc20gf7cwvqa700mqauhsksjj0gj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cFloMUh3NWhtT1ZlZ25H
            ZmoyYStLc1ZDWk9NOWI5UDFRcWI2TDNPWUZBCnpjVWVKOUtoNWtBZVBoWE5YYnky
            Wk5OeU1nWXkrbU5FcmtDUzRqbG1kU3MKLS0tIG85TTJtMU1JT3RBQ05vK2t1NFJ0
            NmNKM2p3OE9xbFQ3VUp2b1QzL2ZPZEUK8kXTqnWT7UfpBld3B3Xz7wxXA2m6sF+v
            uQCZLlnimEHoI7VZDheziPr58GfDRl+KeR7AWgl6FywZTfIcHg3FAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T16:54:18Z"
    mac: ENC[AES256_GCM,data:BbiAP/qKdUaxtHunTVDGK0jlp4W2zVP7ypQXSa/34Fa8c9nq2CRyGqOYCk+BaeXi0ddrDL6M7Cko6JUuvnan7OafH3VsOwKGBRbws69Cjmu6qHLYPcODDuJPBEH0Asa2m/X2Rwmt5Qfbel/XMkltHG3bnFUKgJpFNG5ZZBmCVvg=,iv:IaI9yH6YuAih68q3mR+UAr2KXCVO4S75dC26k4t0yaU=,tag:Tfcd9xlYOcF9yOMNDD+D2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
