apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
data:
    address: ENC[AES256_GCM,data:fLroX9GxafPui+3YazxoZyVyqm9/eOWlh9psT44Y3HPyBysrUPc5c2Vr/f3iEfBsxy7zSfbHyeWBvI92kZXn14prjK1c+5iSiLvhIVQ1qpEwU6Ng57+7ybm88mtx0UENonLMZV0iy1OqTjpFKvidEzhfgSuTp5CTOgdfpDtglzGAQGKoQdDCEO5Jl8hRP85iY2VywbNzOs21gOr3N0bJCMsvgWM=,iv:cNETy+4Q7rOowabCsPXUQwUPxzcZHluTkvPrXKLDvXk=,tag:7RcpF3Q+QhI4xG/0LBCxIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5gkmyjsuwlsucdvpt3z9sk3t6wdtnc20gf7cwvqa700mqauhsksjj0gj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMVhJZyswWTRwUjVtZFNE
            UGM1Q1dLUUNxZDJVcWtHRlEwQzI3eW5uMkg0CmhJQVREWWtEZmhSTUJHMHhOb21k
            REZkcXViYjVjTGhFYjNwelA1WTVFeE0KLS0tIEV0ZlN6TzByZDdRc01taDBnNk93
            cXprRlNBUXphSElQWmRPWGlvc25LR3MKOW83/49+yBf6nYqSdp6FbZjYfz8mpkGq
            6yMLcR2WZFtTMJfuStMjnSJOWxHuYImWTTOdhk0ts9Qi3q1vGocWDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T18:04:00Z"
    mac: ENC[AES256_GCM,data:TxYElAfhtvJUvrbCdfml+TP4lv9sEAwdXZ2Wkn8lulwtoqAUxjHnamuOmBCkPORhbTrc6hNxasTLU1kk3rdKuduEUccQcQ2MdUDbCK0jT39lJ6S03JbBvQomQj32+Ymez713lgXx4eEHwXBfrT45ueqW+oNCa9WzdohJQk88tfc=,iv:zPqPscx+AKr8GKcxexEWVe9nBLzmazYSpl5E7dHeUrI=,tag:z4zoA+F6/fF5XdIKXPyHlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
