apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
data:
    address: ENC[AES256_GCM,data:8GoxNATBE0gTtjm4aPjUZHyUTOWDfALFZDdlaZt4pPh925IYMt8IrikuXSK8Kt20dZeQ65f9G+DQfdviHuV1vaZdWwy6J7MqXTYAn0Y3HEpGhn9IkFtANAFyuvVYGqIpmihwz1YK6C9PxRXHMVbXMBm5m9F1+2Nyljo2Pgpy22UiSufGKb/Lnd4w27jfK+CelJfH4XN+kNY6xtP3GKPZYw5d1xA=,iv:XRv392Dqr4IQIKwU8i2hkUeKw20YdC32NC7L9mhXfl0=,tag:9rztqQn9JNDq78kIJ/moYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-21T17:53:31Z"
    mac: ENC[AES256_GCM,data:o2EnbjjY1AYLiC8/L3LTIKbwH5uI4aOKeWmCT8LHlX9rsmwpRF6CUk0Z6XgPl5joQzGgBbwsPCtKkG1dBn1Eswr5AAwa8+dSTM8kdRdXDOhy9cLorXoyZnjG6xWRmLWDw6Dc2ezw0vN035jEcLZl8tWAAOfT2mNrg8VMonzTkLI=,iv:JEkld+ne+BgG7nfIAjUHUzhztzfYvKhmmLjOqr5MCuM=,tag:J+d/4pLiGkeX79qSbUwRgQ==,type:str]
    pgp:
        - created_at: "2025-11-21T17:53:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+yz/x7sIsGtARAAqib/zhHarCaZOT+gM6Y6OniOAiIN4QnAlDY2rIKCYXd4
            JTLPWr2FkmSGYl9jUY63yxfizoaeGBReTjHyFAM9CB4BYuF8VmlrL9bjJI8U0Mql
            f/8UGbqXyp9VSk+Ha1o6qj8z0H0Jv/V1OVNZTAqc/NnK4c6v/+sIU0211W0ue7yl
            hFBNKaqSDYX7dj3+ZRzouYIEW5VmSK4djn3eqc5nI3rndpeL184INmeCvW6Fa2tq
            95O/dY3qTT4C4H4JbnYcOr6fSzGsfN28eymx+hJt0LOPH6dmjFLOerjUAMUJWZC/
            ph8aCi4eUoFywtac4BAAiFwVp3HUiTJVn3Fcjt/O8PBFcQkAI1d4qneyMD6KbVJx
            GPhpIkYHA5Pg+jMbSmjCNolYEkiBd/cdghFU3XRO2wYDEWLt2qHT9S/3ShdSPW4z
            oNfdDJw9U66JfwqHTlMjUhOy75Xb54X0WMbYuZFwRG7vIMhzF87IgyGxtcdV6cg3
            1Sfk2/47xR7JOdCf7NgUPNCePBpAGLmMZq7xrqHpMLgV7DkrU8n5Zn7SnYD791fb
            rPMAYwbSt2jZfjV/bHwpPW0M1MmeWTxmCqo08HJbAbD/D3NmxyF/tfjKyN4Zxml1
            wXe/+MTEqrrBsLcYIkhIxodnQZGdwsQugtPqku3Yz5Lf9dCi6KXGazz5cqKEkD3S
            XAFb20d3MNIKc0DwAxZtEAcJF9rYzHSWT0VdGK0g20WuVbE1U7kTftuZQ3JFBwrk
            GNIoM3XJOo3HCQ8kvkf53IVLJSaugB59wxvMbw4B9aSMcwWrKmTaHHIPR09i
            =RkfA
            -----END PGP MESSAGE-----
          fp: 4FBF8742DC108D1CBE41957BBD979CE0C5E0FE04
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
