---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: gammatron
    ingress:
      main:
        className: traefik
        annotations:
          hajimari.io/icon: mdi:broadcast
          nginx.ingress.kubernetes.io/whitelist-source-range: null
          traefik.ingress.kubernetes.io/router.middlewares: default-zigbee2mqtt-whitelist@kubernetescrd
    persistence:
      config:
        existingClaim: zigbee2mqtt-config
        type: null
        accessMode: null
        size: null
