---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: default
spec:
  values:
    persistence:
      config:
        size: 2Gi
        retain: true
      metadata:
        size: 10Gi
        retain: true
      media:
        existingClaim: audiobookshelf-media-pvc
        type: null
        accessMode: null
        size: null
      audiobooks:
        existingClaim: audiobookshelf-audiobooks-pvc
        type: null
        accessMode: null
        size: null
