---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: kube-system
spec:
  values:
    defaultDataPath: /var/mnt/longhorn-storage/
    volumes:
      - name: local-volume
        hostPath:
          path: /var/mnt/local-volume
    defaultBackupStore:
      backupTarget: nfs://gammatron.oaklodge.lan:/datapool/longhorn-backups
