---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: gammatron
    persistence:
      config:
        existingClaim: audiobookshelf-config
        type: null
        accessMode: null
        size: null
      metadata:
        existingClaim: audiobookshelf-metadata
        type: null
        accessMode: null
        size: null
      media:
        existingClaim: audiobookshelf-media
        type: null
        accessMode: null
        size: null
      audiobooks:
        existingClaim: audiobookshelf-audiobooks
