---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: gammatron
    persistence:
      config:
        existingClaim: syncthing-config
        type: null
        accessMode: null
        size: null
      videos:
        existingClaim: videos-pvc
    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_syncthing}
        externalTrafficPolicy: Local
        type: LoadBalancer
        ports:
          sync:
            port: 22000
            protocol: TCP
