---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: kube-system
spec:
  secretName: letsencrypt-cert-secret # pragma: allowlist secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - "oaklodge.dev"
    - "*.oaklodge.dev"
    - "*.tiny-kube.oaklodge.dev"
