---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - ./whoami
  - ./audiobookshelf
  - ./videos-vols.yaml
  - ./middleware.yaml
  - ./frigate
  - ./mosquitto
  - ./homeassistant
  - ./zigbee2mqtt
  - ./deluge
  - ./jellyfin
  - ./radarr
  - ./sonarr
  - ./seerr
  - ./unpackerr
  - ./wizarr
  - ./prowlarr
  - ./pg-cluster
  - ./nextcloud
