---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        # intel.feature.node.kubernetes.io/gpu: "true"
        kubernetes.io/hostname: gammatron
      securityContext:
        supplementalGroups: [44, 109] # Extra groups for access to hardware encode/decode
    persistence:
      config:
        existingClaim: plexmediaserver-config
        type: null
        accessMode: null
        size: null
      videos:
        existingClaim: videos-pvc
      transcode:
        type: persistentVolumeClaim
        existingClaim: plexmediaserver-transcode-pvc
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_plex}
