---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: default
spec:
  values:
    ingress:
      main:
        hosts:
          - host: homeassistant-new.${cluster_ext_domain}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        existingClaim: homeassistant-config
        type: null
        accessMode: null
        size: null
