apiVersion: v1
kind: Secret
metadata:
    name: frigate-plus-api-key
    namespace: default
data:
    api-key: ENC[AES256_GCM,data:oMgDal9AWlU9mNo0v2yl0W1EbfiEZ0pjqj08TS0rOwTzYg5PFvVMeu9L5D1sTLpl+ubbokAmQVcRhJAW9XUQyN/uzXKqBspfoT0MoM24yPoZmfuZimR4hQk0R7CoKlrhiICajPybYCA=,iv:oFz/2uoJDsm08ZySgfFM9YV3l95rfuaECPII1OK7btY=,tag:LxkVyExgw09PcmxnOXdu8w==,type:str]
sops:
    age:
        - recipient: age1l5gkmyjsuwlsucdvpt3z9sk3t6wdtnc20gf7cwvqa700mqauhsksjj0gj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVm50eERCT2tKSTBEb00y
            NElCYXVjRVlYYW96SUdhNnFxbnBFdTBISDNRCmd4QUpDZG0yZDY0ZC82NHJDUzZl
            b2ljN3dEeVFlVjBJZWs5SmtFdm5hRFkKLS0tIHl1RDBiZ2ZYSWRvS1h4Sjlybldx
            ckVxd0dOVW83dFVuazZ1ZTR2ek5DbFkKy3Mh/6Jf4/Iyql157Sep4q2e7C7mRTGj
            zTHGblAiJZGKyc4l/AqyKyJjdyIV1K8TnGin+AGl1QPwDbnOgJzO0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T20:08:30Z"
    mac: ENC[AES256_GCM,data:3jrFsIm1Wc2I8DD2elt5sGWYri0TaF01lVCH04fqtezHIcFjwE6BnjNmJlm7LNqWfRQJj4hXBD4WccWSZrmiRLQlWybyIts39F0igyK2Iz1fRAZQp0O3lzd98r6nF6e/Ktd7hXBYtfdujTaRee2PiE+f3s3ugDqlU3lAamxeZN0=,iv:vWmPHg/O9fTSOhxjNdcFSvhJfJZa+j93tbelgdI2ajI=,tag:lKzfa/en0D8CNMxFCWL1dA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
