---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: default
spec:
  values:
    persistence:
      config:
        retain: true
    ingress:
      main:
        className: nginx
        annotations:
          hajimari.io/icon: mdi:jellyfish-outline
        hosts:
          - host: jellyseerr.oaklodge.dev
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
