---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: default
spec:
  values:
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_homeassistant}
    persistence:
      config:
        size: 25Gi
        retain: true
    ingress:
      main:
        className: nginx
        annotations:
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: homeassistant.oaklodge.dev
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
