---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  values:
    persistence:
      config:
        existingClaim: sonarr-config
        type: null
        accessMode: null
        size: null
      videos:
        existingClaim: videos-pvc
      downloads:
        existingClaim: downloads-pvc
