---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/cloudnative-pg/charts
  timeout: 3m
