---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/oaklodge-tiny
  dependsOn:
    - name: infrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      cluster_name: oaklodge-tiny
      cluster_int_domain: tiny-kube.oaklodge.dev
      cluster_ext_domain: tiny-kube.oaklodge.dev
      default_provisioner_scname: local-path
      metallb_ip_homeassistant: 192.168.20.41
      metallb_ip_mqtt: 192.168.20.47
      wl_source_range: 192.168.0.0/16,10.0.0.0/8
