---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: gammatron
    persistence:
      videos:
        existingClaim: videos-pvc
      downloads:
        existingClaim: downloads-pvc
      config:
        existingClaim: radarr-config
        type: null
        accessMode: null
        size: null
