kind: Secret
apiVersion: v1
metadata:
    name: unpackerr-config
    namespace: default
type: Opaque
stringData:
    unpackerr.conf: ENC[AES256_GCM,data:FsoCSiNhwmXmaxhq6XdYly6Ik4WXnPGe6G6R4AqDfF9AFr8j+wWutm/xOuzQwXJ0/91VS0GZHmyAxaHCyG6xoY7eDikhyz0QyGbrjYYHWh1YJH47rMAStawPnWQnhekUEASZDfhG40abSjNNORE57MJlVohPzs/nbJ4cj6llwg1xa/KiN8+h3+pvQZ0jbYOCj62Qw9KgsLeQsTO144lK+GjXyN/pi0FJV1HJI3XfiivQzr1dEEHK5NRzkLG3bZ8rFdMfbFfS4mWkY8xGeFZSySF7mBGR6WUCouBviDoLPu52cw+UHvpQXgpOWJ3J7TL9xvi/TCMJ4hSIykrMpMr/eLOD5rU2KomM2N2VpQzpLY9XmVhjTM+GRClyhrWYp9Q44p9L4xyU7C+5brB0hooUp/47qG78p/ZFkDlqV23T37FQFNSJiyEIqPnURnQXJfZNyFVHWweuNydB6H+xOh6ONs0LDeRzgL3oH7Ko9HbSAD66kejXQGbVXFlTlj3vNO2mZkNZG0Vr6HSAXwJOj1ZtYWuWeQFWOWcxh6fAAynrQ6ReZl3c6z+ONJbnZqt9gJ3A/3b4OZYsOw==,iv:9gVjOCozcmURpDfAab+koXj7Tq9GS96Tu9pJW4o78zM=,tag:PLcr2/JGgDlyQZUgduZuJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5gkmyjsuwlsucdvpt3z9sk3t6wdtnc20gf7cwvqa700mqauhsksjj0gj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWJOQ1ZCT1lkNUF5b0R5
            aHpVTmJHRDJpSUtOUXF5K1U1eFVxWE5SaEFnCno0SGVsdFBVSVpWcEJsSkRtUDh0
            a3hZZWwxRU9TZFhtdW41ejhZWlFxN00KLS0tIE5RaXFBR1lCQ1Y3RjF3MytpWlY5
            OFJEQ0tUM0NuOUpnQkJpeHZEbGx5OEkKUCkPN/M1ceomrrpooLCJ3RyevL6p2+BC
            gQ2PQ4r8kM9NjIcROs8zV8qBCPIizE9b8bkKtfurdLAeZV6EK79gHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T19:46:30Z"
    mac: ENC[AES256_GCM,data:dW3iQtsmeHTM42QRtHe0opKrC6P3JY7eLaXQ8VE3sDjnIIhYJoLvWB2cF9qIka27j4mHS6QzHftL8Jsem/nqWRNwi2euL7+dOKd9876yFAIUOdnEuF9W8EJxm3q4HpmY0Wmkon53ehy7cKdQc7KCDBi3ghtv49ZP2eBF26BGtgU=,iv:VjPrUaJQEhDvDkSLKJ1q4LTzf1yNotVyMkS8fzV5Bww=,tag:SKPlmuGLM72kZqCwmkL6Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
