apiVersion: v1
kind: Secret
metadata:
    name: frigate-plus-api-key
    namespace: default
data:
    api-key: ENC[AES256_GCM,data:Bfwky55MGj954MRWeOHwanjuE3+lgbOgXA6578QcDjg84cETu+x1/9YCHiDaYzNdff35yN85rRgetikX9IeV4LuxZONhMsyKoGYlnt9V6TkDwns3hTvSp+yKXZajmHazoVUaKvKr1y8=,iv:6YxibXfJTy5r7EQLhPQYlRTph0HZRPdqFMnmNWim9D4=,tag:Va9ybnik71u4iDIOH+d/aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5gkmyjsuwlsucdvpt3z9sk3t6wdtnc20gf7cwvqa700mqauhsksjj0gj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL3JRVVpHdnlMYW5RWitD
            UE1WTS9uNVNKZjBmSy9odGJKTU1IUVJzWGtzCnhXTjB3cjlTYnhyMExPSXd4WHk3
            THRITDRrWlZHNER3UzZpV2Q4N2lmbjgKLS0tIFcvT1BpcFZZcHFLY0R6aWEvUEgw
            YUk3MmluQmdJeDF6U1dPQ3BVQ1kxbzAKrSWd2KeWMqmTj3saatoomoUNwcVMSnNF
            a4Oa/EqZYRhXroveabCQkMyOZz2Tu5/UiJeusxSE4d2RnB58ACTJHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T11:02:20Z"
    mac: ENC[AES256_GCM,data:mWS+wx1Po0fLDN7FbfYloLORcN8lMbQMPccnXs0OuPuiAbSdrzJ8EWR4aPTX6gEnLlS1/OMh3MulPJr8NCRv2i5FvpKp1ufVHd0T1T/CHQ3V2NXZv3fGlsBsLc2DeB+C159jo1K3vaQ9Qsbzk8zEn+1oZNNFkh70UhTsxptNDvM=,iv:7CVjx6ZXHLOD+MoS7pSlgiVsKjztLRNimWHkDDIiMwc=,tag:E+IDNsIGxDc1G8O2gQygJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
