---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      image:
        registry: registry.k8s.io
        image: ingress-nginx/controller
        tag: v1.4.0
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_nginx}
      extraArgs:
        default-ssl-certificate: kube-system/letsencrypt-cert-secret
      ingressClassResource:
        default: true
      config:
        force-ssl-redirect: "true"
