apiVersion: v1
kind: Secret
metadata:
    name: deluge-client-secret
    namespace: default
data:
    deluge-username: ENC[AES256_GCM,data:o/NsIysAuQk=,iv:8ok8T3/ez+Sa9w9m/zdkBJ9VpRebmDtvpJug2HBH7/A=,tag:FNMUx2CbMgwF+GleK529sQ==,type:str]
    deluge-password: ENC[AES256_GCM,data:pJHKgjUBAOcPvsVs,iv:3v2R2cpnxApUfATI09h44AyP0egd0fpGAc0Xn2dTpJs=,tag:WZgbj7YxPZ27U2OHFO1Y7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l5gkmyjsuwlsucdvpt3z9sk3t6wdtnc20gf7cwvqa700mqauhsksjj0gj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWUVRU0xxTmJDMlpQcStt
            bnBweWR1eUVHVmRIaUNWYmdoS2UwdDVFS2tRCkF5am5tdnpuNWNRblIxOFBIZU5K
            d0VrSy96REtkc0RUWE1vNkVKS1h6NnMKLS0tIHBERVpqT0Z2TkJSbmhtNFhYU1cx
            dm1lNXozYVpWRHFWUDFSVDlXd3NDMHcK2LyqnRZDlMY/16rJJV1+CvI1UACQ4WEz
            VeBLPYcuFxzijf6VJJZnwzJtaSjUr7JvAtp/pmtWBZCpzkBV6j6IDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T14:32:59Z"
    mac: ENC[AES256_GCM,data:gf9A3PWHFBS/lyk9WuBX7doGfdbR/nn5pwFezNEPnPeOOHaujpbqLveYdUVi9iSkqHbC4PMjl/vN4VMtov4P59/YlPn17uHX//QQxXHgXy3+dk3MVTgGVrdgxO4dA+MLORrpv6vpoQO2s/+WhmSRnXIdzdfXYHkNCI2pGPxYSfU=,iv:cdtboPPq0slNBMLnq7K7o0v0Ck3KxiFX5oZV8k9PFIA=,tag:CTMso0sYTVdkv9A4E3QLYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
