---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deluge-cleanup
  namespace: default
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: deluge-cleanup
              image: ghcr.io/garvbox/autodl:v0.3.0
              env:
                - name: DELUGE_CLIENT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: deluge-client-secret
                      key: deluge-username
                - name: DELUGE_CLIENT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: deluge-client-secret
                      key: deluge-password
                - name: DELUGE_CLIENT_HOST
                  value: deluge-daemon.default.svc.cluster.local
                - name: DELUGE_CLIENT_PORT
                  value: "58846"
