---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  values:
    controllers:
      main:
        replicas: 0
    persistence:
      downloads:
        existingClaim: nfs-downloads-pvc
        globalMounts:
          - path: /datapool/downloads
      config:
        retain: true
    service:
      daemon:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_deluge}
        controller: main
        ports:
          torrents:
            port: 55066
            targetPort: 55066
            protocol: TCP
          admin:
            port: 58846
            targetPort: 58846
            protocol: TCP
