apiVersion: v1
kind: Secret
metadata:
    name: deesl-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:J0UbuaF1OwRI3UUXGtHSXxX6ygD3nN104sQCuVgikqq+fqFuahGWd+vsGx1NTuUznOFFZg2nk+FZozr9f7fWuX4kWLSq1i9XmMgDZ9Tv2w1wgRQ=,iv:UiXrHsxBSBLB6lNFHm5lWGIV680OpmIsq0eFpGcbnNA=,tag:0KBBHPYRF3S+UcexeVBs/w==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:MQ5vOH/YUVXUQNdHyQiQKkFfTnZVZNnMNpNNmjQBdJT3f5k3VQxlxQeE6dONI32ei/thnNW8lwonRgX8vbCYHKe6j0g83A5G,iv:+ypv5hvYr7OjI/08Jx9m4xvZL+k3PGJ3YtGPrVA86Yo=,tag:twJHL04A4ApLXbTRX35Jtw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:7riDYQgvDsT7IyAhM/LNYoMiCP9BtNjcH+IF0vMVJ9rEA3E=,iv:/Aj76tk9Bn9sdqQyGBQipARUgkIXOttbkJXQ5v1COjQ=,tag:/g5gNV/ouzaWPuw4Lw3zuQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:VAMtvgHMau5/VqKFAEit43lodYd1zLJwYXjEH459kWhOYbVleGunmsXrHBCoZgzoWfWNJdfV8J28Zh9B6sRS9Q==,iv:Z5sIDPNs1lgalWqa9gDJN6P1gO+tjTPnEhAdRjSFUfY=,tag:VfWvrL5+0tEbiidA7hXKMQ==,type:str]
sops:
    age:
        - recipient: age1l5gkmyjsuwlsucdvpt3z9sk3t6wdtnc20gf7cwvqa700mqauhsksjj0gj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TnpDQTVESHBnMjY1MFJE
            bCtlU1RpMDBOYjVpTzAzMTlBdkcrUDZpTUhZCnFFUStWM0dJSm1Td1h1ZUJmSUlK
            UVZ3aEtSZFYxSjJocXRSc215cXhzODAKLS0tIEdJbWprbnNCUjJZM3djWTVmTDZk
            b3JjL21IQ1JaRGl6eWlpOXNHMHRUL00KnISWm2jz3UgF8D46unp09Kw3fMV/IcxT
            0l+QQj0NK2sO010wlCxx1LJNUOxyzaQftrRa0/69NblQPmoRMjhb/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T22:55:18Z"
    mac: ENC[AES256_GCM,data:HGaISZ1mQ6SB7o8iyz0dXv2H/4L7RN+IOu8xd0ZOTRAuyH4vjegeEvIN53fDPAXA0JyWVVvJkDsqQxA7LvOyWj/3s742LbarBnDGw9kMyQ41p2Qi3RZhLCtk9gJ+2ymV4xR3A2S+fsFfT+ub0WU8pW2/QYDvfQfap1TMJBmIRKU=,iv:/icKQTzWxXHHV/TvknZDy8e3aboxgCxc8qwQV6fF+sA=,tag:X7DNipVcYAvTVw3qfw9Dng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
