---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.10.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  targetNamespace: longhorn-system
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.${cluster_ext_domain}
      annotations:
        hajimari.io/icon: mdi:cow
        nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
