---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-nextcloud-data-pv
  namespace: default
spec:
  storageClassName: local-datapool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datapool/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-datapool
  volumeName: local-nextcloud-data-pv
  resources:
    requests:
      storage: 1Mi
