---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.7.9823
            env:
              TZ: "Europe/Dublin"
              ADVERTISE_IP: "https://plex.${cluster_ext_domain}/"
              # PLEX_CLAIM:
              PLEX_PREFERENCE_1: "LanNetworksBandwidth=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12"
              PLEX_PREFERENCE_2: "TranscoderQuality=0"
              PLEX_PREFERENCE_3: "TranscoderH264BackgroundPreset=fast"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    defaultPodOptions:
      securityContext:
        runAsUser: 6666
        runAsGroup: 6666
        fsGroup: 6666
        fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        className: nginx
        annotations:
          hajimari.io/icon: mdi:plex
        hosts:
          - host: plex.${cluster_ext_domain}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    service:
      main:
        controller: main
        ports:
          http:
            port: 32400
            protocol: TCP
          dlna-tcp:
            port: 32469
            protocol: TCP
          dlna-udp:
            port: 1900
            protocol: UDP
          plex-companion:
            port: 3005
            protocol: TCP
          discovery-udp:
            port: 5353
            protocol: UDP
          plex-roku:
            port: 8324
            protocol: TCP
          gdm-32410:
            port: 32410
            protocol: UDP
          gdm-32412:
            port: 32412
            protocol: UDP
          gdm-32413:
            port: 32413
            protocol: UDP
          gdm-32414:
            port: 32414
            protocol: UDP
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
      transcode:
        type: emptyDir
