---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/tautulli/tautulli
              tag: v2.15.2
            env:
              TZ: "Europe/Dublin"
            command: ["python", "Tautulli.py"]
            args: [
              "--config", "/config/config.ini",
              "--datadir", "/config",
              "--port", "8181"
            ]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &port 8181
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup: *probes
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      main:
        className: nginx
        annotations:
          hajimari.io/icon: mdi:chart-box
        hosts:
          - host: tautulli.${cluster_ext_domain}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10G
