---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/unpackerr/unpackerr
              tag: 0.14.5
            env:
              TZ: "Europe/Dublin"
    defaultPodOptions:
      securityContext:
        runAsUser: 6666
        runAsGroup: 6666
        fsGroup: 6666
        fsGroupChangePolicy: "OnRootMismatch"
