---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /${host_path_base}/postgres-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: postgres-data-pv
  resources:
    requests:
      storage: 5Gi
