---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/gammasite-prod
  dependsOn:
    - name: infrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      cluster_int_domain: kube.gammasite.lan
      cluster_ext_domain: gammasite.garvbox.net
      default_provisioner_scname: local-path
      host_path_base: /rocketpool/kube/pvs
      metallb_ip_deluge: 192.168.0.61
      metallb_ip_plex: 192.168.0.62
      metallb_ip_factorio: 192.168.0.63
      metallb_ip_syncthing: 192.168.0.64
      metallb_ip_mqtt: 192.168.0.66
      metallb_ip_influx: 192.168.0.67
      metallb_ip_jellyfin: 192.168.0.68
      wl_source_range: 192.168.0.0/16,10.0.0.0/8
