---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/gammasite-prod
  dependsOn:
    - name: infra-core-install
  # Enable Encryption using sops-gpg secret pre-loaded with ansible
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      metallb_ip_dns: 192.168.20.19
      metallb_ip_range: 192.168.20.20-192.168.20.29
      metallb_ip_nginx: 192.168.20.20
      wl_source_range: 192.168.0.0/16,10.0.0.0/8
      cluster_name: oaklodge
      cluster_ext_domain: oaklodge.dev
      cluster_int_domain: gammatron-kube.oaklodge.lan
      default_provisioner_scname: local-path
      host_path_base: /rocketpool/kube/pvs
      admin_email: gonarvib@protonmail.com
      le_url: https://acme-v02.api.letsencrypt.org/directory
