---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/gammasite-prod
  dependsOn:
    - name: infra-core-install
  # Enable Encryption using sops-gpg secret pre-loaded with ansible
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      metallb_ip_dns: 192.168.0.45
      metallb_ip_range: 192.168.0.51-192.168.0.69
      metallb_ip_nginx: 192.168.0.60
      # These are only used in the apps kustomization but listed here to avoid duplication
      metallb_ip_deluge: 192.168.0.61
      metallb_ip_plex: 192.168.0.62
      metallb_ip_factorio: 192.168.0.63
      metallb_ip_syncthing: 192.168.0.64
      metallb_ip_mqtt: 192.168.0.66
      metallb_ip_influx: 192.168.0.67
      metallb_ip_jellyfin: 192.168.0.68
      metallb_ip_unifi: 192.168.0.69
      wl_source_range: 192.168.0.0/16,10.0.0.0/8
      cluster_name: oaklodge
      cluster_ext_domain: oaklodge.dev
      cluster_int_domain: kube.oaklodge.lan
      default_provisioner_scname: local-path
      host_path_base: /rocketpool/kube/pvs
      admin_email: gonarvib@protonmail.com
      le_url: https://acme-v02.api.letsencrypt.org/directory
