---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  values:
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_frigate}
    persistence:
      config:
        existingClaim: frigate-config
        type: null
        accessMode: null
        size: null
      media:
        existingClaim: frigate-data-pvc
        type: null
        accessMode: null
        size: null
