---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  values:
    controllers:
      main:
        containers:
          main:
            resources:
              requests:
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
            securityContext:
              privileged: true
              supplementalGroups: [44, 109] # Extra groups for access to hardware encode/decode
            env:
              PLUS_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: frigate-plus-api-key
                    key: api-key
    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
        kubernetes.io/hostname: gammatron
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_frigate}
    persistence:
      config:
        existingClaim: frigate-config
        type: null
        accessMode: null
        size: null
      media:
        existingClaim: frigate-media-pvc
        type: null
        accessMode: null
        size: null
