---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config-pv
  namespace: default
spec:
  storageClassName: local-data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/frigate-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-data
  volumeName: frigate-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media-pv
  namespace: default
spec:
  storageClassName: local-data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/datapool/cctv/frigate"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-data
  volumeName: frigate-media-pv
  resources:
    requests:
      storage: 1Mi
